### ISSUE TITLE
eval.cc reference

### ISSUE THREAD

**Issue by zhoujf620** [yunzhu-li/blupig-gomoku#7]
感谢作者的开源代码！

关于 eval.cc，想请问是否有 pattern generation and match 算法的 reference，目前的 code+comment 理解起来还是有点困难。

**Comment by zhoujf620** [comment]
在 eval.h 文件
```C++
    // A single direction pattern
    struct DirectionPattern {
        char min_occurrence;  // Minimum number of occurrences to match
        char length;          // Length of pattern (pieces in a row)
        char block_count;     // Number of ends blocked by edge or the other player (0-2)
        char space_count;     // Number of spaces in the middle of pattern (-1: Ignore value)
    };
```
注明 block_count \in {0, 1, 2}，但在eval.cc 文件中，存在如 {2, 4, -1,  1}，{1, 4, -1,  1}的 情况，请教该作何理解？

**Comment by yunzhu-li** [comment]
你好，这个程序已经很久没维护了，我可能也不太熟悉😂 ， 算法是自己弄的，思维比较混乱，也没有 reference。block_count 的问题根据 [这里](https://github.com/yunzhu-li/blupig-gomoku/blob/master/src/ai/eval.cc#L134) 应该是 -1 的时候允许 0, 1, 2 中的任何值。
